version: 2.1
orbs:
  go: circleci/go@2.2.3
jobs:
  unit-test:
    executor:
      name: go/default
      tag: '1.23'
    steps:
      - checkout
      - go/mod-download
      - go/test:
          build_ldflags: '-X ''main.Version=v1.0.0'''
          build_tags: integration,e2e
          covermode: atomic
          failfast: true
          no_output_timeout: 15m
          race: true
          timeout: 15m
workflows:
  main:
    jobs:
      - unit-test
